name: AutoCareiOS
options:
  bundleIdPrefix: com.ivan
  deploymentTarget:
    iOS: '16.0'

configs:
  Debug:
    buildSettings:
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
  Release:
    buildSettings:
      SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"

targets:
  AutoCareiOS:
    type: application
    platform: iOS
    sources:
      - AutoCareiOS
      - Features
      - Core
      - Service
      - ViewModels
    resources:
      - AutoCareiOS/Assets.xcassets
      - AutoCareiOS/LaunchScreen.storyboard
    info:
      path: AutoCareiOS/Info.plist
    dependencies: []
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ivan.AutoCareiOS
